using System.Globalization;
using System.Linq;
using Content.Shared._Starlight.Commands;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Starlight.Administration.UI.Tabs.AdminTab;

[GenerateTypedNameReferences]
public sealed partial class SLAdminShuttleWindow : DefaultWindow
{
    [Dependency] private IClientConGroupController _console = null!;
    [Dependency] private IClientConsoleHost _host = null!;

    private const string CallShuttleCmd = "> eshuttle:callshuttle";
    private const string RecallShuttleCmd = "> eshuttle:recallshuttle";

    // this stinks but whateverrrrrrrrrr, need this otherwise its ambiguous and the timespan will parse via its own dumb rules.
    private static readonly HashSet<string> _formats =
    [
        @"m\:ss",
        @"m\:ss\.f",
        @"m\:ss\.ff",
        @"m\:ss\.fff",
        @"h\:mm\:ss",
        @"h\:mm\:ss\.f",
        @"h\:mm\:ss\.ff",
        @"h\:mm\:ss\.fff",
    ];

    public SLAdminShuttleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        CallShuttleButton.OnPressed += _ =>
        {
            // Extract total seconds from input
            if (!TimeSpan.TryParseExact(CallShuttleTime.Text, [.. _formats], CultureInfo.InvariantCulture,
                    out var duration))
            {
                CommandMarkup.Error(_host.LocalShell, "Failed to parse time string.");
                return;
            }

            var time = (float)duration.TotalSeconds;
            if (!_console.CanCommand(CallShuttleCmd)) return;
            _host.ExecuteCommand($"{CallShuttleCmd} {time}");
        };
        RecallShuttleButton.OnPressed += _ =>
        {
            if (!_console.CanCommand(RecallShuttleCmd)) return;
            _host.ExecuteCommand(RecallShuttleCmd);
        };
    }
}

